% Author: Atanu Giri
% Date: 01/02/2024

function [Sal_P2L1_id, Ghr_P2L1_id, Sal_P2L1L3_id, Ghr_P2L1L3_id] = extract_sal_ghr_ids(varargin)
% This function extracts P2L1 Saline, P2L1 Ghrelin, P2L1L3 Saline, P2L1L3
% Ghrelin ids

if numel(varargin) < 1
    datasource = 'live_database';
    conn = database(datasource,'postgres','1234');
else
   conn =  varargin{1};
end

%% Sal P2L1 ids
sal_L1_male_Q = "SELECT id, health, genotype, tasktypedone, referencetime, " + ...
    "subjectid, gender FROM live_table WHERE (referencetime " + ...
    "LIKE '%06/30/2022%' OR referencetime LIKE '%07/05/2022%' OR " + ...
    "referencetime LIKE '%07/18/2022%') AND gender " + ...
    "ILIKE 'Male' AND UPPER(subjectid) <> UPPER('none')";
sal_L1_male_Data = fetch(conn, sal_L1_male_Q);

sal_L1_female_Q = "SELECT id, health, genotype, tasktypedone, referencetime, " + ...
    "subjectid, gender FROM live_table WHERE referencetime " + ...
    "LIKE '%07/01/2022%' AND gender ILIKE 'Female' AND health = '2 hour Saline' " + ...
    "AND UPPER(subjectid) <> UPPER('none')";
sal_L1_female_Data = fetch(conn, sal_L1_female_Q);

Sal_P2L1_Data = vertcat(sal_L1_male_Data, sal_L1_female_Data);
Sal_P2L1_id = Sal_P2L1_Data.id;

%% Ghr P2L1 ids
ghr_L1_male_Q = "SELECT id, health, genotype, tasktypedone, referencetime, " + ...
    "subjectid, gender FROM live_table WHERE (referencetime " + ...
    "LIKE '%06/27/2022%' OR referencetime LIKE '%07/06/2022%' OR " + ...
    "referencetime LIKE '%07/07/2022%') AND gender " + ...
    "ILIKE 'Male' AND UPPER(subjectid) <> UPPER('none')";
ghr_L1_male_Data = fetch(conn, ghr_L1_male_Q);

ghr_L1_female_Q = "SELECT id, health, genotype, tasktypedone, referencetime, " + ...
    "subjectid, gender FROM live_table WHERE (referencetime " + ...
    "LIKE '%06/28/2022%' OR referencetime LIKE '%07/12/2022%' OR " + ...
    "referencetime LIKE '%07/13/2022%') AND (health = '2 Hour Ghrelin' OR " + ...
    "health = '2 Hours Ghrelin') AND gender ILIKE 'Female' " + ...
    "AND UPPER(subjectid) <> UPPER('none')";
ghr_L1_female_Data = fetch(conn, ghr_L1_female_Q);

Ghr_P2L1_Data = vertcat(ghr_L1_male_Data, ghr_L1_female_Data);
Ghr_P2L1_id = Ghr_P2L1_Data.id;

%% Sal P2L1L3 ids
sal_L1L3_male_Q = "SELECT id, health, genotype, tasktypedone, referencetime, " + ...
    "subjectid, gender FROM live_table WHERE referencetime " + ...
    "LIKE '%07/19/2022%' AND gender " + ...
    "ILIKE 'Male' AND UPPER(subjectid) <> UPPER('none')";
sal_L1L3_male_Data = fetch(conn, sal_L1L3_male_Q);

sal_L1L3_female_Q = "SELECT id, health, genotype, tasktypedone, referencetime, " + ...
    "subjectid, gender FROM live_table WHERE (referencetime " + ...
    "LIKE '%07/26/2022%' OR referencetime LIKE '%07/29/2022%') AND gender " + ...
    "ILIKE 'Female' AND UPPER(subjectid) <> UPPER('none') AND health <> 'N/A'";
sal_L1L3_female_Data = fetch(conn, sal_L1L3_female_Q);

Sal_P2L1L3_Data = vertcat(sal_L1L3_male_Data, sal_L1L3_female_Data);
Sal_P2L1L3_id = Sal_P2L1L3_Data.id;

%% Ghr P2L1L3 ids
ghr_L1L3_male_Q = "SELECT id, health, genotype, tasktypedone, referencetime, " + ...
    "subjectid, gender FROM live_table WHERE referencetime " + ...
    "LIKE '%07/08/2022%' AND gender " + ...
    "ILIKE 'Male' AND UPPER(subjectid) <> UPPER('none')";
ghr_L1L3_male_Data = fetch(conn, ghr_L1L3_male_Q);

ghr_L1L3_female_Q = "SELECT id, health, genotype, tasktypedone, referencetime, " + ...
    "subjectid, gender FROM live_table WHERE referencetime " + ...
    "LIKE '%07/14/2022%' AND gender " + ...
    "ILIKE 'Female' AND UPPER(subjectid) <> UPPER('none')";
ghr_L1L3_female_Data = fetch(conn, ghr_L1L3_female_Q);

Ghr_P2L1L3_Data = vertcat(ghr_L1L3_male_Data, ghr_L1L3_female_Data);
Ghr_P2L1L3_id = Ghr_P2L1L3_Data.id;

end